# Generated by Django 5.1 on 2024-08-18 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0002_booking_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='buffer_time',
            field=models.DurationField(default=datetime.timedelta(seconds=900)),
        ),
    ]
