# Generated by Django 5.1 on 2024-08-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0003_booking_buffer_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
