# Generated by Django 5.1 on 2024-08-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0004_booking_booking_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(max_length=10),
        ),
    ]
