# Generated by Django 5.1 on 2024-08-18 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0005_alter_booking_booking_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='buffer_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
