# Generated by Django 5.1 on 2024-08-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0006_alter_booking_buffer_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(),
        ),
    ]
