# Generated by Django 5.1 on 2024-08-19 01:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0008_booking_total_endtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_endtime',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 19, 0, 0)),
        ),
    ]
