# Generated by Django 5.1 on 2024-08-27 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0010_alter_booking_total_endtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_endtime',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 27, 0, 0)),
        ),
    ]
