# Generated by Django 5.1 on 2024-09-01 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0012_alter_booking_total_endtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_endtime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 0, 0)),
        ),
    ]
