# Generated by Django 5.1 on 2024-09-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0013_booking_status_alter_booking_total_endtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment',
            field=models.CharField(default='Null', max_length=50),
        ),
    ]
