# Generated by Django 5.1 on 2024-09-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0014_booking_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment',
            field=models.CharField(default='Pending..', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Pending..', max_length=50),
        ),
    ]
