# Generated by Django 5.1 on 2024-09-02 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0015_alter_booking_payment_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_endtime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 0, 0)),
        ),
    ]
